version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.single  # 单服务
    ports:
      - "3000:3000"

  NotifyEverything:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-compose.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    environment:
      - KV_URL=${KV_URL}
      - KV_REST_API_URL=${KV_REST_API_URL}
      - KV_REST_API_TOKEN=${KV_REST_API_TOKEN}
      - KV_REST_API_READ_ONLY_TOKEN=${KV_REST_API_READ_ONLY_TOKEN}